
on:
  push:
    paths:
      - '.github/workflows/example-openssl.yaml'
    branches: master
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-and-package:
    name: Build openssl example
    runs-on: 'ubuntu-20.04'
    container:
      image: debian:buster
    
    steps:
    - name: Install prerequisites
      run: |
        apt-get update
        apt-get install -y curl sudo git build-essential

    - name: Download and install latest cross-toolchain version
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/nesto-software/cross-toolchain-armhf/master/scripts/install-from-release.sh)"

    - name: Source the toolchain's installer script and use cross-toolchain to compile openssl
      run: |
        echo "$(curl -fsSL https://raw.githubusercontent.com/nesto-software/cross-toolchain-armhf/master/scripts/install-from-release.sh)" > /tmp/init-cross-toolchain.sh
        source /tmp/init-cross-toolchain.sh
        export STAGING_DIR=/usr/raspberry-build/staging
        mkdir -p "${STAGING_DIR}"
        git clone https://github.com/openssl/openssl.git /tmp/openssl
        cd /tmp/openssl
        git checkout OpenSSL_1_1_1d
        ./Configure linux-generic32 --cross-compile-prefix=${TOOLCHAIN_PATH}/${TOOLCHAIN}- --prefix=$STAGING_DIR/usr/local/
        make