
on:
  push:
    paths:
      - '.github/workflows/example-openssl.yaml'
    branches: master
  workflow_dispatch:

jobs:
  build-and-package:
    name: Build openssl example
    runs-on: 'ubuntu-20.04'
    container:
      image: debian:buster
    
    steps:
    - name: Install prerequisites
      run: |
        apt-get update
        apt-get install -y curl sudo

    - name: Download and install latest toolchain
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/nesto-software/cross-toolchain-armhf/master/scripts/install-from-release.sh)"